config/routes.rb
Rails.application.routes.draw do

  resources :slab_project_tasks
  patch 'slab_project_tasks/complete/:id', to: 'slab_project_tasks#complete'
  resources :slab_projects 
  patch 'slab_projects/complete/:id', to: 'slab_projects#complete'
  post 'auth/login'
  post 'auth/register'
  resources :projects
  get 'password/reset'
  post 'password/reset'
  get 'password/forgot'
  post 'password/forgot'
  resources :users
  get 'users/new'
  get 'users/create'
  get 'home/index'
  get 'home/login'
  get 'home/xd'
  post 'home/login'
  post 'home/index'
  
  root 'home#index'
  resources :crypto_prices
  resources :cryptocurrencies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
    RISK_FACTORS = [
        "LOW", "MEDIUM", "HIGH"
    ]

    validates :name, presence: true, uniqueness: true
    validates :ticker_symbol, presence: true, uniqueness: true
    validates :risk_factor, presence: true, inclusion: { in:RISK_FACTORS }
    #validates :name, uniqueness: true
    validate :validate_ticker_symbol #note is VALIDATE and NOT VALIDATES
    has_many :stock_prices
    before_save :capitalize_ticker_symbol

    def capitalize_ticker_symbol
        self.ticker_symbol = self.ticker_symbol.upcase
    end

    def validate_ticker_symbol
        if self.ticker_symbol.present?
            if self.ticker_symbol.size < 2 or self.ticker_symbol.size > 4
                self.errors.add(:ticker_symbol, "Size should be >= 2 or <= 4")
            end
        end
    end
end

app/models/crypto_price.rb
class CryptoPrice < ApplicationRecord
  belongs_to :cryptocurrency
end

app/models/cryptocurrency.rb
class Cryptocurrency < ApplicationRecord
    has_many :crypto_prices
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :company
end

app/models/slab_project.rb
class SlabProject < ApplicationRecord
    has_many :slab_project_task, dependent: :destroy
end

app/models/slab_project_task.rb
class SlabProjectTask < ApplicationRecord
  belongs_to :slab_project
end

app/models/stock_price.rb
class StockPrice < ApplicationRecord
  belongs_to :company
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  
  skip_before_action :verify_authenticity_token, only: %i[ login register ]
  before_action :auth_params, only: %i[ login register ]

  def login
    p request
    c = {ok: true}
    render :json => c
  end

  def register
    c = { ok: true }
    render :json => c
  end

  def auth_params
    params.require(:auth).permit(:email, :password, :p)
  end
end

app/controllers/crypto_prices_controller.rb
class CryptoPricesController < ApplicationController
  before_action :set_crypto_price, only: %i[ show edit update destroy ]

  # GET /crypto_prices or /crypto_prices.json
  def index
    @crypto_prices = CryptoPrice.all
  end

  # GET /crypto_prices/1 or /crypto_prices/1.json
  def show
  end

  # GET /crypto_prices/new
  def new
    @crypto_price = CryptoPrice.new
  end

  # GET /crypto_prices/1/edit
  def edit
  end

  # POST /crypto_prices or /crypto_prices.json
  def create
    @crypto_price = CryptoPrice.new(crypto_price_params)

    respond_to do |format|
      if @crypto_price.save
        format.html { redirect_to @crypto_price, notice: "Crypto price was successfully created." }
        format.json { render :show, status: :created, location: @crypto_price }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @crypto_price.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crypto_prices/1 or /crypto_prices/1.json
  def update
    respond_to do |format|
      if @crypto_price.update(crypto_price_params)
        format.html { redirect_to @crypto_price, notice: "Crypto price was successfully updated." }
        format.json { render :show, status: :ok, location: @crypto_price }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @crypto_price.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crypto_prices/1 or /crypto_prices/1.json
  def destroy
    @crypto_price.destroy
    respond_to do |format|
      format.html { redirect_to crypto_prices_url, notice: "Crypto price was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crypto_price
      @crypto_price = CryptoPrice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def crypto_price_params
      params.require(:crypto_price).permit(:price, :cryptocurrency_id, :captured_at)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    p params
    render :json => User.first()
  end
  def login
    if params['username']
      #user = User.find_by_username(params['username'])
      user = User.find_by(username: params['username'])
      #@user = user['username']
      @valid = user.authenticate(params['password'])
    end 
  end
  def xd
    render :json => User.last
  end
end

app/controllers/task_controller.rb
class TaskController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end
  def show 
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      p @user.errors.count
      redirect_to @user, alert: "User created successfully"
    else
      redirect_to new_user_path, alert: "Error creating user"
    end
  end

  def user_params
    params.require(:user).permit(:username, :password, :salt, :encrypted_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/crypto_prices_helper.rb
module CryptoPricesHelper
end

app/helpers/home_helper.rb
module HomeHelper
    def articles(query)
        require 'rss'
        require 'open-uri'
        url = "https://news.google.com/rss/search?cf=all&g1?en-US&pz=1&q=#{query}&gl=US&ceid=US:en"
        URI.open(url) do |rss|
            RSS::Parser.parse(rss)
        end
    end
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/crypto_prices/_form.html.erb
<%= form_with(model: crypto_price) do |form| %>
  <% if crypto_price.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crypto_price.errors.count, "error") %> prohibited this crypto_price from being saved:</h2>

      <ul>
        <% crypto_price.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :cryptocurrency_id %>
    <%= form.collection_select :cryptocurrency_id, Cryptocurrency.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :captured_at %>
    <%= form.date_select :captured_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/crypto_prices/edit.html.erb
<h1>Editing Crypto Price</h1>

<%= render 'form', crypto_price: @crypto_price %>

<%= link_to 'Show', @crypto_price %> |
<%= link_to 'Back', crypto_prices_path %>

app/views/crypto_prices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Crypto Prices</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th>Cryptocurrency</th>
      <th>Captured at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @crypto_prices.each do |crypto_price| %>
      <tr>
        <td><%= crypto_price.price %></td>
        <td><%= crypto_price.cryptocurrency_id %></td>
        <td><%= crypto_price.captured_at %></td>
        <td><%= link_to 'Show', crypto_price %></td>
        <td><%= link_to 'Edit', edit_crypto_price_path(crypto_price) %></td>
        <td><%= link_to 'Destroy', crypto_price, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Crypto Price', new_crypto_price_path %>

app/views/crypto_prices/new.html.erb
<h1>New Crypto Price</h1>

<%= render 'form', crypto_price: @crypto_price %>

<%= link_to 'Back', crypto_prices_path %>

app/views/crypto_prices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @crypto_price.price %>
</p>

<p>
  <strong>Cryptocurrency:</strong>
  <%= @crypto_price.cryptocurrency.name %>
</p>

<p>
  <strong>Captured at:</strong>
  <%= @crypto_price.captured_at %>
</p>

<%= link_to 'Edit', edit_crypto_price_path(@crypto_price) %> |
<%= link_to 'Back', crypto_prices_path %>