config/routes.rb
Rails.application.routes.draw do

  resources :slab_project_tasks
  patch 'slab_project_tasks/complete/:id', to: 'slab_project_tasks#complete'
  resources :slab_projects 
  patch 'slab_projects/complete/:id', to: 'slab_projects#complete'
  post 'auth/login'
  post 'auth/register'
  resources :projects
  get 'password/reset'
  post 'password/reset'
  get 'password/forgot'
  post 'password/forgot'
  resources :users
  get 'users/new'
  get 'users/create'
  get 'home/index'
  get 'home/login'
  get 'home/xd'
  post 'home/login'
  post 'home/index'
  
  root 'home#index'
  resources :crypto_prices
  resources :cryptocurrencies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
    RISK_FACTORS = [
        "LOW", "MEDIUM", "HIGH"
    ]

    validates :name, presence: true, uniqueness: true
    validates :ticker_symbol, presence: true, uniqueness: true
    validates :risk_factor, presence: true, inclusion: { in:RISK_FACTORS }
    #validates :name, uniqueness: true
    validate :validate_ticker_symbol #note is VALIDATE and NOT VALIDATES
    has_many :stock_prices
    before_save :capitalize_ticker_symbol

    def capitalize_ticker_symbol
        self.ticker_symbol = self.ticker_symbol.upcase
    end

    def validate_ticker_symbol
        if self.ticker_symbol.present?
            if self.ticker_symbol.size < 2 or self.ticker_symbol.size > 4
                self.errors.add(:ticker_symbol, "Size should be >= 2 or <= 4")
            end
        end
    end
end

app/models/crypto_price.rb
class CryptoPrice < ApplicationRecord
  belongs_to :cryptocurrency
end

app/models/cryptocurrency.rb
class Cryptocurrency < ApplicationRecord
    has_many :crypto_prices
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :company
end

app/models/slab_project.rb
class SlabProject < ApplicationRecord
    has_many :slab_project_task, dependent: :destroy
end

app/models/slab_project_task.rb
class SlabProjectTask < ApplicationRecord
  belongs_to :slab_project
end

app/models/stock_price.rb
class StockPrice < ApplicationRecord
  belongs_to :company
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  
  skip_before_action :verify_authenticity_token, only: %i[ login register ]
  before_action :auth_params, only: %i[ login register ]

  def login
    p request
    c = {ok: true}
    render :json => c
  end

  def register
    c = { ok: true }
    render :json => c
  end

  def auth_params
    params.require(:auth).permit(:email, :password, :p)
  end
end

app/controllers/cryptocurrencies_controller.rb
class CryptocurrenciesController < ApplicationController
  before_action :set_cryptocurrency, only: %i[ show edit update destroy ]

  # GET /cryptocurrencies or /cryptocurrencies.json
  def index
    @cryptocurrencies = Cryptocurrency.all
  end

  # GET /cryptocurrencies/1 or /cryptocurrencies/1.json
  def show
  end

  # GET /cryptocurrencies/new
  def new
    @cryptocurrency = Cryptocurrency.new
  end

  # GET /cryptocurrencies/1/edit
  def edit
  end

  # POST /cryptocurrencies or /cryptocurrencies.json
  def create
    @cryptocurrency = Cryptocurrency.new(cryptocurrency_params)

    respond_to do |format|
      if @cryptocurrency.save
        format.html { redirect_to @cryptocurrency, notice: "Cryptocurrency was successfully created." }
        format.json { render :show, status: :created, location: @cryptocurrency }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cryptocurrency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cryptocurrencies/1 or /cryptocurrencies/1.json
  def update
    respond_to do |format|
      if @cryptocurrency.update(cryptocurrency_params)
        format.html { redirect_to @cryptocurrency, notice: "Cryptocurrency was successfully updated." }
        format.json { render :show, status: :ok, location: @cryptocurrency }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cryptocurrency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cryptocurrencies/1 or /cryptocurrencies/1.json
  def destroy
    @cryptocurrency.destroy
    respond_to do |format|
      format.html { redirect_to cryptocurrencies_url, notice: "Cryptocurrency was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cryptocurrency
      @cryptocurrency = Cryptocurrency.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cryptocurrency_params
      params.require(:cryptocurrency).permit(:name, :started_at)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    p params
    render :json => User.first()
  end
  def login
    if params['username']
      #user = User.find_by_username(params['username'])
      user = User.find_by(username: params['username'])
      #@user = user['username']
      @valid = user.authenticate(params['password'])
    end 
  end
  def xd
    render :json => User.last
  end
end

app/controllers/task_controller.rb
class TaskController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end
  def show 
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      p @user.errors.count
      redirect_to @user, alert: "User created successfully"
    else
      redirect_to new_user_path, alert: "Error creating user"
    end
  end

  def user_params
    params.require(:user).permit(:username, :password, :salt, :encrypted_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/cryptocurrencies_helper.rb
module CryptocurrenciesHelper
end

app/helpers/home_helper.rb
module HomeHelper
    def articles(query)
        require 'rss'
        require 'open-uri'
        url = "https://news.google.com/rss/search?cf=all&g1?en-US&pz=1&q=#{query}&gl=US&ceid=US:en"
        URI.open(url) do |rss|
            RSS::Parser.parse(rss)
        end
    end
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cryptocurrencies/_form.html.erb
<%= form_with(model: cryptocurrency) do |form| %>
  <% if cryptocurrency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cryptocurrency.errors.count, "error") %> prohibited this cryptocurrency from being saved:</h2>

      <ul>
        <% cryptocurrency.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :started_at %>
    <%= form.date_select :started_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cryptocurrencies/edit.html.erb
<h1>Editing Cryptocurrency</h1>

<%= render 'form', cryptocurrency: @cryptocurrency %>

<%= link_to 'Show', @cryptocurrency %> |
<%= link_to 'Back', cryptocurrencies_path %>

app/views/cryptocurrencies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cryptocurrencies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Started at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cryptocurrencies.each do |cryptocurrency| %>
      <tr>
        <td><%= cryptocurrency.name %></td>
        <td><%= cryptocurrency.started_at %></td>
        <td><%= link_to 'Show', cryptocurrency %></td>
        <td><%= link_to 'Edit', edit_cryptocurrency_path(cryptocurrency) %></td>
        <td><%= link_to 'Destroy', cryptocurrency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cryptocurrency', new_cryptocurrency_path %>

app/views/cryptocurrencies/new.html.erb
<h1>New Cryptocurrency</h1>

<%= render 'form', cryptocurrency: @cryptocurrency %>

<%= link_to 'Back', cryptocurrencies_path %>

app/views/cryptocurrencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cryptocurrency.name %>
</p>

<p>
  <strong>Started at:</strong>
  <%= @cryptocurrency.started_at %>
</p>

<%= link_to 'Edit', edit_cryptocurrency_path(@cryptocurrency) %> |
<%= link_to 'Back', cryptocurrencies_path %>

<hr>

<% @cryptocurrency.crypto_prices.each do |o| %>
  <li>
    <%= o.price %>
  </li>
<% end %>