config/routes.rb
Rails.application.routes.draw do

  resources :slab_project_tasks
  patch 'slab_project_tasks/complete/:id', to: 'slab_project_tasks#complete'
  resources :slab_projects 
  patch 'slab_projects/complete/:id', to: 'slab_projects#complete'
  post 'auth/login'
  post 'auth/register'
  resources :projects
  get 'password/reset'
  post 'password/reset'
  get 'password/forgot'
  post 'password/forgot'
  resources :users
  get 'users/new'
  get 'users/create'
  get 'home/index'
  get 'home/login'
  get 'home/xd'
  post 'home/login'
  post 'home/index'
  
  root 'home#index'
  resources :crypto_prices
  resources :cryptocurrencies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
    RISK_FACTORS = [
        "LOW", "MEDIUM", "HIGH"
    ]

    validates :name, presence: true, uniqueness: true
    validates :ticker_symbol, presence: true, uniqueness: true
    validates :risk_factor, presence: true, inclusion: { in:RISK_FACTORS }
    #validates :name, uniqueness: true
    validate :validate_ticker_symbol #note is VALIDATE and NOT VALIDATES
    has_many :stock_prices
    before_save :capitalize_ticker_symbol

    def capitalize_ticker_symbol
        self.ticker_symbol = self.ticker_symbol.upcase
    end

    def validate_ticker_symbol
        if self.ticker_symbol.present?
            if self.ticker_symbol.size < 2 or self.ticker_symbol.size > 4
                self.errors.add(:ticker_symbol, "Size should be >= 2 or <= 4")
            end
        end
    end
end

app/models/crypto_price.rb
class CryptoPrice < ApplicationRecord
  belongs_to :cryptocurrency
end

app/models/cryptocurrency.rb
class Cryptocurrency < ApplicationRecord
    has_many :crypto_prices
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :company
end

app/models/slab_project.rb
class SlabProject < ApplicationRecord
    has_many :slab_project_task, dependent: :destroy
end

app/models/slab_project_task.rb
class SlabProjectTask < ApplicationRecord
  belongs_to :slab_project
end

app/models/stock_price.rb
class StockPrice < ApplicationRecord
  belongs_to :company
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  
  skip_before_action :verify_authenticity_token, only: %i[ login register ]
  before_action :auth_params, only: %i[ login register ]

  def login
    p request
    c = {ok: true}
    render :json => c
  end

  def register
    c = { ok: true }
    render :json => c
  end

  def auth_params
    params.require(:auth).permit(:email, :password, :p)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    p params
    render :json => User.first()
  end
  def login
    if params['username']
      #user = User.find_by_username(params['username'])
      user = User.find_by(username: params['username'])
      #@user = user['username']
      @valid = user.authenticate(params['password'])
    end 
  end
  def xd
    render :json => User.last
  end
end

app/controllers/slab_projects_controller.rb
class SlabProjectsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_slab_project, only: %i[ show edit update destroy complete ]

  # GET /slab_projects or /slab_projects.json
  def index
    @slab_projects = SlabProject.all
    render :json => @slab_projects.to_json(:include => :slab_project_task)
  end

  # GET /slab_projects/1 or /slab_projects/1.json
  def show
    render :json => @slab_project
  end

  # GET /slab_projects/new
  def new
    @slab_project = SlabProject.new
  end

  # GET /slab_projects/1/edit
  def edit
  end

  # POST /slab_projects or /slab_projects.json
  def create
    @slab_project = SlabProject.new(slab_project_params)

    respond_to do |format|
      if @slab_project.save
        SlabMailer.with(project: @slab_project).project_created.deliver_later

        format.html { redirect_to @slab_project, notice: "Slab project was successfully created." }
        format.json { render :show, status: :created, location: @slab_project }

      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @slab_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slab_projects/1 or /slab_projects/1.json
  def update
    respond_to do |format|
      if @slab_project.update(slab_project_params)
        format.html { redirect_to @slab_project, notice: "Slab project was successfully updated." }
        format.json { render :show, status: :ok, location: @slab_project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @slab_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slab_projects/1 or /slab_projects/1.json
  def destroy
    @slab_project.destroy
    respond_to do |format|
      format.html { redirect_to slab_projects_url, notice: "Slab project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def complete
    if @slab_project.slab_project_task.size > 0
      p @slab_project.slab_project_task
      if !@slab_project.slab_project_task.all? {|x| x.status == "Done"}
        render :json => { errors: ["Some tasks are not completed"] }
      else
        @slab_project.status = "Done"
        if @slab_project.save
          
          render :json => { message: "Completed" }
        else
          render :json => { message: "Error ocurred during completition" }
        end
      end
    else
      render :json => { errors: ["The project has not tasks"] }
    end
  rescue
    render :json => { message: "Error ocurred during completition" }, status: :bad_request
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slab_project
      @slab_project = SlabProject.find(params[:id])
    rescue
      render :json => {errors: ["No slab project with id #{params[:id]}"]}
    end

    # Only allow a list of trusted parameters through.
    def slab_project_params
      params.require(:slab_project).permit(:name, :description, :start_at, :finish_at)
    end
end

app/controllers/task_controller.rb
class TaskController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end
  def show 
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      p @user.errors.count
      redirect_to @user, alert: "User created successfully"
    else
      redirect_to new_user_path, alert: "Error creating user"
    end
  end

  def user_params
    params.require(:user).permit(:username, :password, :salt, :encrypted_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/home_helper.rb
module HomeHelper
    def articles(query)
        require 'rss'
        require 'open-uri'
        url = "https://news.google.com/rss/search?cf=all&g1?en-US&pz=1&q=#{query}&gl=US&ceid=US:en"
        URI.open(url) do |rss|
            RSS::Parser.parse(rss)
        end
    end
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/slab_projects_helper.rb
module SlabProjectsHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/slab_projects/_form.html.erb
<%= form_with(model: slab_project) do |form| %>
  <% if slab_project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(slab_project.errors.count, "error") %> prohibited this slab_project from being saved:</h2>

      <ul>
        <% slab_project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :start_at %>
    <%= form.date_select :start_at %>
  </div>

  <div class="field">
    <%= form.label :finish_at %>
    <%= form.date_select :finish_at %>
  </div>

  <div class="field">
    <%= form.label :finished_at %>
    <%= form.date_select :finished_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/slab_projects/complete.html.erb
aaaaa

app/views/slab_projects/edit.html.erb
<h1>Editing Slab Project</h1>

<%= render 'form', slab_project: @slab_project %>

<%= link_to 'Show', @slab_project %> |
<%= link_to 'Back', slab_projects_path %>

app/views/slab_projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Slab Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Status</th>
      <th>Start at</th>
      <th>Finish at</th>
      <th>Finished at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @slab_projects.each do |slab_project| %>
      <tr>
        <td><%= slab_project.name %></td>
        <td><%= slab_project.description %></td>
        <td><%= slab_project.status %></td>
        <td><%= slab_project.start_at %></td>
        <td><%= slab_project.finish_at %></td>
        <td><%= slab_project.finished_at %></td>
        <td><%= link_to 'Show', slab_project %></td>
        <td><%= link_to 'Edit', edit_slab_project_path(slab_project) %></td>
        <td><%= link_to 'Destroy', slab_project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Slab Project', new_slab_project_path %>

app/views/slab_projects/new.html.erb
<h1>New Slab Project</h1>

<%= render 'form', slab_project: @slab_project %>

<%= link_to 'Back', slab_projects_path %>

app/views/slab_projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @slab_project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @slab_project.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @slab_project.status %>
</p>

<p>
  <strong>Start at:</strong>
  <%= @slab_project.start_at %>
</p>

<p>
  <strong>Finish at:</strong>
  <%= @slab_project.finish_at %>
</p>

<p>
  <strong>Finished at:</strong>
  <%= @slab_project.finished_at %>
</p>

<%= link_to 'Edit', edit_slab_project_path(@slab_project) %> |
<%= link_to 'Back', slab_projects_path %>